// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ls-Kypitldu7Z_1Ml1DqhhPKVb2oADg',
    appId: '1:762468017991:web:5860c8da3cf62927ee4e62',
    messagingSenderId: '762468017991',
    projectId: 'expense-tracker-ad0a6',
    authDomain: 'expense-tracker-ad0a6.firebaseapp.com',
    storageBucket: 'expense-tracker-ad0a6.firebasestorage.app',
    measurementId: 'G-F16NMK7KGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQoG-iKDSsrNubxasXnxeVyYvU1DvLrYw',
    appId: '1:762468017991:android:dc9782d76cb0f655ee4e62',
    messagingSenderId: '762468017991',
    projectId: 'expense-tracker-ad0a6',
    storageBucket: 'expense-tracker-ad0a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgMpuaKk8Phu8Cz_Za-eQZ2xWOELgF9g',
    appId: '1:762468017991:ios:e787a42c0bc6e843ee4e62',
    messagingSenderId: '762468017991',
    projectId: 'expense-tracker-ad0a6',
    storageBucket: 'expense-tracker-ad0a6.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYgMpuaKk8Phu8Cz_Za-eQZ2xWOELgF9g',
    appId: '1:762468017991:ios:e787a42c0bc6e843ee4e62',
    messagingSenderId: '762468017991',
    projectId: 'expense-tracker-ad0a6',
    storageBucket: 'expense-tracker-ad0a6.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ls-Kypitldu7Z_1Ml1DqhhPKVb2oADg',
    appId: '1:762468017991:web:07251302715ecabdee4e62',
    messagingSenderId: '762468017991',
    projectId: 'expense-tracker-ad0a6',
    authDomain: 'expense-tracker-ad0a6.firebaseapp.com',
    storageBucket: 'expense-tracker-ad0a6.firebasestorage.app',
    measurementId: 'G-64QND5L4PC',
  );
}
